services:
  db:
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: example_123
    # mssql server image isn't available for arm64 architecture, so we use azure-sql instead
    #image: mcr.microsoft.com/azure-sql-edge:1.0.4
    # If you really want to use MS SQL Server, uncomment the following line
    #image: mcr.microsoft.com/mssql/server
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    ports:
      - "1433:1433"
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P example_123 -No -Q 'SELECT 1' || exit 1" ]
      interval: 10s
      retries: 10
      start_period: 10s
      timeout: 3s
    volumes:
      - ./mssql_data:/var/opt/mssql

  server:
    depends_on:
      - db
    image: server
    build:
      context: .
      dockerfile: Server/Dockerfile
    restart: unless-stopped
    ports:
      - 5021:5021
      - 7099:7099
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5021;https://+:7099
      - ASPNETCORE_Kestrel__Certificates__Default__Password=1234
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
    
  client:
    depends_on:
      - server
    image: client
    build:
      context: .
      dockerfile: Client/Dockerfile
    restart: unless-stopped
    ports:
      - 5141:80
      - 7102:443

volumes:
  mssql_data: